name: Scheduled JavaScript Runner

on:
  schedule:
    # # Runs every 5 minutes
    # - cron: '*/5 * * * *'
    - cron: '30 5 * * 3'    # Runs every Wednesday at 12:00 AM IST (5:30 AM UTC)
    - cron: '35 5 * * 3'    # Runs every Wednesday at 12:05 AM IST (5:35 AM UTC)
    - cron: '35 11 * * 2'    # Runs every Tuesday at 5:05 PM IST (11:35 AM UTC)
    # # Runs at 9:00 AM UTC daily (adjust to your preferred time)
    # - cron: '0 9 * * *'
    # # Runs every Friday at 12:00 AM
    # - cron: '0 0 * * 5'
    # # Runs every 7 days
    # - cron: '0 0 */7 * *'
  workflow_dispatch: 

jobs:
  run-js-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or the version you need

      - name: Print IST and UTC Times
        run: |
          echo "Current UTC Time: $(date -u)"
          echo "Current IST Time: $(TZ='Asia/Kolkata' date)"

      # - name: Install Dependencies (if needed)
      #   run: npm install

      - name: Run some action
        run: echo "Hello, World!"

      - name: Run myfile.js
        run: node myfile.js
